# Generated by Django 4.1.5 on 2023-02-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Client_status',
        ),
    ]
